# Default values for ddns-update.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

### Parameters for DynamicDNSUpdate scrypt (Mandatory)

config:
  dns_zone: ""
  timezone: UTC-9

secret:
  existingSecret: ""
  aws_access_key_id:
     value: ""
  #  secretKey: ""
  aws_secret_access_key:
     value: ""
  #  secretKey: ""

### Parameters for Kubernetes

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/orz-style/ddns-update
  tag: "2.2.0"

imagePullSecrets: []

cronjob:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 10

job:
  completions: 1
  backoffLimit: 3

persistence:
  accessModes: ReadWriteOnce
  annotations: {}
  storageClass: ""
  size: 100M
  volumeMode: Filesystem

nodeSelector: {}

tolerations: []

affinity: {}
