apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddns-update.fullname" . }}
  labels:
    {{- include "ddns-update.labels" . | nindent 4 }}
data:
  dns-zone: {{ .Values.config.dns_zone }}
  timezone: {{ .Values.config.timezone }}

