apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ddns-update.fullname" . }}
  labels:
    {{- include "ddns-update.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  accessModes:
    - {{ default "ReadWriteOnce" .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ default "100M" .Values.persistence.size | quote }}
  {{- with .Values.persistence.volumeMode }}
  volumeMode: {{ . }}
  {{- end }}

