{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddns-update.fullname" . }}
  labels:
    {{- include "ddns-update.labels" . | nindent 4 }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.secret.aws_access_key_id.value | b64enc | quote }}
  aws_secret_access_key: {{ .Values.secret.aws_secret_access_key.value | b64enc | quote }}
{{- end }}
